Slide Strategy
PermutaTriangle/Tilings pull request #285
Opened 2020-11-19 15:35 UTC by JonSteinn

2020-11-23 10:42 UTC, christianbean requested changes

2020-11-23 10:42 UTC, christianbean commented on tilings/algorithms/__init__.py
> +    "gp_slide_inverse",
Most of these functions are too specific to the sliding stuff. I think we should think about creating a `Sliding` class for containing the algorithm and these methods (more akin to the way the other algorithms are done).

2020-11-23 10:42 UTC, christianbean commented on tilings/strategies/sliding.py
> +    return t
Do these really need functions?

2020-11-23 10:42 UTC, christianbean commented on tilings/strategies/sliding.py
> +    return _tmp_func
I understand why you have given these their own methods. The methods on `GriddedPerm` maybe should take into account the context in which the symmetry is taken in a simple way. This is probably an issue for a future PR.

2020-11-23 10:42 UTC, christianbean commented on tilings/strategies/sliding.py
> +    return t
Even the case where you apply two symmetries could be a single application of one symmetry - i.e. the anti-diagonal or complement symmetries (I think).

2020-11-23 10:42 UTC, christianbean commented on tilings/strategies/sliding.py
> +    """
You can remove 'probably' now.

2020-11-23 10:42 UTC, christianbean commented on tilings/strategies/sliding.py
> +        raise NotImplementedError()
We'll need to implement the json methods before accepting. I'll add some things to test files that you need to make sure pass.

2020-11-23 10:42 UTC, christianbean commented on tilings/strategies/sliding.py
> +    """
This need rewritten.

2020-11-23 21:01 UTC, christianbean approved these changes

2020-11-24 10:29 UTC, enadeau requested changes
I've left a few comments most are easy fix but there's a most substantial one about the argument for the sliding strategy. Perhaps we can discuss it in meeting

2020-11-24 10:29 UTC, enadeau commented on tilings/strategies/sliding.py
> +        sliding: Sliding,
Isn't that a bit too much that the strategy needs to store the whole sliding algorithm? If I compare with the fusion algorithm, only the column or row fused is stored and the algorithm can be recomputed if needed.

2020-11-24 10:29 UTC, enadeau commented on tilings/strategies/sliding.py
> +        return str(self)
Can you implement a proper repr? That could come in handy for debugging

2020-11-24 13:20 UTC, enadeau requested changes

2020-11-24 13:20 UTC, enadeau commented on tilings/strategies/sliding.py
> +    def __call__(
You don't actually need to define that, it's already defined on the super class

2020-11-24 13:25 UTC, enadeau approved these changes

2020-11-24 13:53 UTC, merged